import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os


# ============================================================
# CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Titanic Survival Predictor",
    page_icon="🚢",
    layout="wide"
)


# ============================================================
# LOAD MODEL ARTIFACTS
# ============================================================

BASE_DIR = os.path.dirname(os.path.abspath(__file__))


def load_file(filename):
    return joblib.load(os.path.join(BASE_DIR, filename))


titanic_knn = load_file("titanic_knn.pkl")
titanic_dt = load_file("titanic_dt.pkl")
titanic_lr = load_file("titanic_lr.pkl")
titanic_rf = load_file("titanic_rf.pkl")

titanic_scaler = load_file("titanic_scaler.pkl")
titanic_features = load_file("titanic_features.pkl")

train_path = os.path.join(BASE_DIR, "titanic_train.pkl")
legacy_train_path = os.path.join(BASE_DIR, "titanic_train.pk1")

if os.path.exists(train_path):
    titanic_train = load_file("titanic_train.pkl")
elif os.path.exists(legacy_train_path):
    titanic_train = load_file("titanic_train.pk1")
else:
    raise FileNotFoundError("Could not find titanic_train.pkl or titanic_train.pk1")


# ============================================================
# SESSION STATE
# ============================================================

if "titanic_prediction" not in st.session_state:
    st.session_state.titanic_prediction = None


# ============================================================
# PAGE HEADER
# ============================================================

st.title("🚢 Titanic Survival Predictor")

st.markdown(
    """
    ### Put yourself aboard the Titanic

    Enter a passenger profile and compare how four machine-learning
    models estimate your chance of survival.

    The application uses the same selected features and preprocessing
    pipeline used during model training.
    """
)

st.caption("Interactive ML showcase • Python • Scikit-learn • Streamlit")

st.divider()

# ============================================================
# TITANIC SURVIVAL PREDICTOR
# ============================================================
# ============================================================

st.header("🚢 Titanic Survival Predictor")

st.markdown(
    """
    Imagine yourself aboard the RMS Titanic.

    Enter your passenger details and the models will estimate your
    **survival probability** based on the characteristics used during
    training.
    """
)
st.caption(
    "This prediction is generated by machine learning models for educational purposes based on historical passenger patterns. Your actual fate aboard the Titanic remains thankfully untestable."
)


# ============================================================
# PASSENGER IDENTITY
# ============================================================

st.subheader("Your Passenger Identity")

col1, col2 = st.columns(2)

with col1:

    passenger_name = st.text_input(
        "Passenger Name",
        value="John Smith"
    )

with col2:

    occupation = st.text_input(
        "Occupation",
        value="Passenger"
    )


# ============================================================
# EXTRA FLAVOUR DETAILS
# These DO NOT enter the ML model
# ============================================================

with st.expander("Additional passenger details (not used for prediction)"):

    flavour_col1, flavour_col2, flavour_col3 = st.columns(3)

    with flavour_col1:

        height = st.text_input(
            "Height(cm)",
            value="Unknown"
        )

    with flavour_col2:

        weight = st.text_input(
            "Weight(kg)",
            value="Unknown"
        )
    with flavour_col3:

        Embarked = st.selectbox(
        "Embarked",
        options=[1, 2, 3],
        format_func=lambda x: {
            1: "Southampton(England)",
            2: "Cherbourg(France)",
            3: "Queenstown(Cobh, Ireland)"
        }[x]            
        )

# ============================================================
# TITANIC MODEL INPUTS
# ============================================================

st.subheader("Passenger Characteristics")

col1, col2, col3 = st.columns(3)


# ------------------------------------------------------------
# Passenger Class
# ------------------------------------------------------------

with col1:

    pclass = st.selectbox(
        "Passenger Class",
        options=[1, 2, 3],
        format_func=lambda x: {
            1: "1st Class",
            2: "2nd Class",
            3: "3rd Class"
        }[x]
    )
    st.caption(
        """1st class is highest, 3rd is lowest. 1st class was most expensive and reserved for high social status people."""
    )


# ------------------------------------------------------------
# Sex
# ------------------------------------------------------------

with col2:

    sex = st.selectbox(
        "Sex",
        options=["Female", "Male"]
    )


# ------------------------------------------------------------
# Age
# ------------------------------------------------------------

with col3:

    age = st.slider(
        "Age",
        min_value=1,
        max_value=80,
        value=18,
        step=1
    )


# ============================================================
# TITLE / FAMILY
# ============================================================

col1, col2, col3 = st.columns(3)


# ------------------------------------------------------------
# Title
# ------------------------------------------------------------

with col1:

    if sex == "Male":

        if age <= 12:
            title_options = [
                "Master",
                "Other/Noble or Professional Title"
            ]
        else:
            title_options = [
                "Mr.",
                "Other/Noble or Professional Title"
            ]

    else:

        title_options = [
            "Miss",
            "Mrs.",
            "Other/Noble or Professional Title"
        ]


    title = st.selectbox(
    "Title",
    options=title_options,
    help=(
        "Master is used for young boys. "
        "Other includes uncommon titles such as Lady, Sir, "
        "Dr., Captain, Colonel, Major, Don, Dona, and Countess."
        )
    )


# ------------------------------------------------------------
# Family Size
# ------------------------------------------------------------

with col2:

    family_size = st.slider(
        "Family Size",
        min_value=1,
        max_value=11,
        value=1,
        step=1
    )
    st.caption(
        """Including you and all your family. Brother, sister, mother, spouse, or father."""
    )


# ------------------------------------------------------------
# Is Alone
# ------------------------------------------------------------

with col3:

    is_alone = int(family_size == 1)

    st.write("Travelling alone?")

    if is_alone:

        st.info("Yes")

    else:

        st.info("No")


# ============================================================
# ENCODING
# ============================================================

sex_encoding = {
    "Female": 0,
    "Male": 1
}

title_encoding = {
    "Master": 0,
    "Miss": 1,
    "Mr.": 2,
    "Mrs.": 3,
    "Other/Noble or Professional Title": 4
}


# ============================================================
# TITANIC PREDICTION BUTTON
# ============================================================

predict_titanic = st.button(
    "⚓ Calculate My Survival Probability",
    type="primary",
    use_container_width=True
)

if predict_titanic:
    # ========================================================
    # CREATE USER INPUT
    # ========================================================

    input_tdf = pd.DataFrame(
        [[
            pclass,
            sex_encoding[sex],
            age,
            title_encoding[title],
            family_size,
            is_alone
        ]],
        columns=titanic_features
    )


    # ========================================================
    # SCALE INPUT
    #
    # KNN + Logistic Regression were trained using scaling.
    # Decision Tree + Random Forest were trained without it.
    # ========================================================

    input_tscaled = titanic_scaler.transform(
        input_tdf
    )


    # ========================================================
    # MODEL PROBABILITIES
    # ========================================================

    knn_probability = titanic_knn.predict_proba(
        input_tscaled
    )[0][1]

    lr_probability = titanic_lr.predict_proba(
        input_tscaled
    )[0][1]

    dt_probability = titanic_dt.predict_proba(
        input_tdf
    )[0][1]

    rf_probability = titanic_rf.predict_proba(
        input_tdf
    )[0][1]


    # ========================================================
    # STORE MODEL RESULTS
    # ========================================================

    titanic_probabilities = {
        "KNN": knn_probability,
        "Logistic Regression": lr_probability,
        "Decision Tree": dt_probability,
        "Random Forest": rf_probability
    }


    # ========================================================
    # ENSEMBLE
    # Average the four model probabilities
    # ========================================================

    survival_probability = np.mean(
        list(titanic_probabilities.values())
    )

    survival_percentage = survival_probability * 100

    st.session_state.titanic_prediction = {
        "survival_probability": survival_probability,
        "survival_percentage": survival_percentage,
        "knn": knn_probability,
        "lr": lr_probability,
        "dt": dt_probability,
        "rf": rf_probability,
        "input": input_tdf.copy(),
        "passenger_name": passenger_name,
        "age": age,
        "sex": sex,
        "pclass": pclass,
        "title": title,
        "family_size": family_size,
        "is_alone": is_alone
    }
    result = st.session_state.titanic_prediction

    survival_probability = result["survival_probability"]
    survival_percentage = result["survival_percentage"]

    knn_probability = result["knn"]
    lr_probability = result["lr"]
    dt_probability = result["dt"]
    rf_probability = result["rf"]


# ============================================================
# DISPLAY LAST PREDICTION
# ============================================================

if st.session_state.titanic_prediction is not None:

    result = st.session_state.titanic_prediction

    survival_probability = result["survival_probability"]
    survival_percentage = result["survival_percentage"]
    knn_probability = result["knn"]
    lr_probability = result["lr"]
    dt_probability = result["dt"]
    rf_probability = result["rf"]

    input_tdf = result["input"]
    passenger_name = result["passenger_name"]
    age = result["age"]
    sex = result["sex"]
    pclass = result["pclass"]
    title = result["title"]
    family_size = result["family_size"]
    is_alone = result["is_alone"]


    # ========================================================
    # RESULT
    # ========================================================

    st.divider()

    st.header(
        f"⚓ {passenger_name}'s Titanic Fate"
    )

    st.metric(
        "Estimated Survival Probability",
        f"{survival_percentage:.1f}%"
    )

    st.progress(
        int(round(survival_percentage))
    )


    # ========================================================
    # RESULT MESSAGE
    # ========================================================

    if survival_percentage >= 75:

        st.success(
            f"Your estimated survival probability is "
            f"**{survival_percentage:.1f}%**. "
            "The models are relatively optimistic about your chances."
        )

    elif survival_percentage >= 50:

        st.warning(
            f"Your estimated survival probability is "
            f"**{survival_percentage:.1f}%**. "
            "You are somewhere in the middle of the historical chaos."
        )

    else:

        st.error(
            f"Your estimated survival probability is "
            f"**{survival_percentage:.1f}%**. "
            "I'm sure you'll survive from your resilience and determination. It's just a model prediction anyway..."
        )


    # ========================================================
    # INDIVIDUAL MODEL RESULTS
    # ========================================================

    st.subheader("How the Four Models See You")

    col1, col2, col3, col4 = st.columns(4)

    model_columns = [
        (col1, "KNN", knn_probability),
        (col2, "Logistic Regression", lr_probability),
        (col3, "Decision Tree", dt_probability),
        (col4, "Random Forest", rf_probability)
    ]

    for column, model_name, probability in model_columns:

        with column:

            st.metric(
                model_name,
                f"{probability * 100:.1f}%"
            )


    # ========================================================
    # USER INPUT SUMMARY
    # ========================================================

    with st.expander("View model input"):

        st.dataframe(
            input_tdf,
            use_container_width=True,
            hide_index=True
        )


    # ========================================================
    # HISTORICAL DOPPELGÄNGER
    # ========================================================

    st.divider()

    st.header("👤 Your Historical Doppelgänger")

    st.markdown(
        """
        Rather than simply finding someone with the same predicted
        survival probability, we look for a passenger whose actual
        circumstances were similar to yours.
        """
    )


    # ========================================================
    # PREPARE HISTORICAL DATA
    # ========================================================

    historical = titanic_train.copy()


    # ========================================================
    # CALCULATE FEATURE SIMILARITY
    # ========================================================

    # Age similarity
    #
    # A difference of 0 years = 1.0
    # A difference of 10+ years = 0.0

    historical["AgeScore"] = (
        1 -
        abs(historical["Age"] - age) / 30
    ).clip(0, 1)


    # Sex similarity

    historical["SexScore"] = (
        historical["Sex"] == sex_encoding[sex]
    ).astype(float)


    # Passenger class similarity

    historical["PclassScore"] = (
        historical["Pclass"] == pclass
    ).astype(float)


    # Title similarity

    historical["TitleScore"] = (
        historical["Title"] == title_encoding[title]
    ).astype(float)


    # Family size similarity

    historical["FamilyScore"] = (
        1 -
        abs(historical["FamilySize"] - family_size) / 6
    ).clip(0, 1)


    # Alone status similarity

    historical["AloneScore"] = (
        historical["IsAlone"] == is_alone
    ).astype(float)


    # ========================================================
    # OVERALL SIMILARITY
    # ========================================================

    historical["Similarity"] = (

        historical["AgeScore"] * 0.30 +

        historical["SexScore"] * 0.25 +

        historical["PclassScore"] * 0.20 +

        historical["TitleScore"] * 0.10 +

        historical["FamilyScore"] * 0.10 +

        historical["AloneScore"] * 0.05
    )


    # ========================================================
    # GET HISTORICAL MODEL PROBABILITIES
    # ========================================================

    historical_input = historical[
        titanic_features
    ].copy()


    # KNN + Logistic Regression use scaled data

    historical_scaled = titanic_scaler.transform(
        historical_input
    )


    historical["KNNProbability"] = (
        titanic_knn.predict_proba(
            historical_scaled
        )[:, 1]
    )


    historical["LRProbability"] = (
        titanic_lr.predict_proba(
            historical_scaled
        )[:, 1]
    )


    # Decision Tree + Random Forest use unscaled data

    historical["DTProbability"] = (
        titanic_dt.predict_proba(
            historical_input
        )[:, 1]
    )


    historical["RFProbability"] = (
        titanic_rf.predict_proba(
            historical_input
        )[:, 1]
    )


    # ========================================================
    # ENSEMBLE PROBABILITY
    # ========================================================

    historical["SurvivalProbability"] = (

        historical["KNNProbability"] +

        historical["LRProbability"] +

        historical["DTProbability"] +

        historical["RFProbability"]

    ) / 4


    # ========================================================
    # FIND SIMILAR PASSENGERS FIRST
    # ========================================================

    # Keep only the most similar passengers.
    #
    # This prevents a completely different person from winning
    # simply because their ML probability happens to be similar.

    similar_passengers = historical[
        historical["Similarity"] >= 0.70
    ].copy()


    # If very few passengers meet the threshold,
    # use the top 25 most similar passengers instead.

    if len(similar_passengers) < 10:

        similar_passengers = historical.nlargest(
            25,
            "Similarity"
        ).copy()


    # ========================================================
    # USE SURVIVAL PROBABILITY AS SECONDARY MATCH
    # ========================================================

    similar_passengers["ProbabilityDifference"] = abs(
        similar_passengers["SurvivalProbability"]
        - survival_probability
    )


    # Sort primarily by similarity,
    # and secondarily by probability difference.

    similar_passengers = similar_passengers.sort_values(
        by=[
            "Similarity",
            "ProbabilityDifference"
        ],
        ascending=[
            False,
            True
        ]
    )


    # Take the best match

    historical_person = similar_passengers.iloc[0]


    # ========================================================
    # EXTRACT INFORMATION
    # ========================================================

    actual_name = historical_person["Name"]

    actual_age = historical_person["Age"]

    actual_sex = historical_person["Sex"]

    actual_class = historical_person["Pclass"]

    actual_title = historical_person["Title"]

    actual_family_size = historical_person["FamilySize"]

    actual_is_alone = historical_person["IsAlone"]

    actual_survived = historical_person["Survived"]

    actual_probability = (
        historical_person["SurvivalProbability"] * 100
    )

    similarity_percentage = (
        historical_person["Similarity"] * 100
    )


    # ========================================================
    # CONVERT ENCODINGS BACK TO HUMAN READABLE VALUES
    # ========================================================

    sex_reverse = {
        0: "Female",
        1: "Male"
    }


    title_reverse = {
        0: "Master",
        1: "Miss",
        2: "Mr",
        3: "Mrs",
        4: "Other"
    }


    readable_sex = sex_reverse.get(
        int(actual_sex),
        "Unknown"
    )


    readable_title = title_reverse.get(
        int(actual_title),
        "Other"
    )


    # ========================================================
    # DISPLAY DOPPELGÄNGER
    # ========================================================

    st.subheader(actual_name)


    col1, col2 = st.columns(2)


    with col1:

        st.write(
            f"**Age:** {actual_age:.0f}"
        )

        st.write(
            f"**Sex:** {readable_sex}"
        )

        st.write(
            f"**Title:** {readable_title}"
        )

        st.write(
            f"**Passenger Class:** {actual_class}"
        )

        st.write(
            f"**Family Size:** {actual_family_size}"
        )

        if actual_is_alone:

            st.write(
                "**Travelling Alone:** Yes"
            )

        else:

            st.write(
                "**Travelling Alone:** No"
            )


    with col2:

        st.metric(
            "Historical Passenger's Modelled Survival",
            f"{actual_probability:.1f}%"
        )

        st.metric(
            "Similarity to You",
            f"{similarity_percentage:.1f}%"
        )

        probability_difference = abs(
            survival_percentage - actual_probability
        )

        st.caption(
            f"Their modelled survival probability is "
            f"{probability_difference:.1f} percentage points "
            f"from yours."
        )


    # ========================================================
    # ACTUAL OUTCOME
    # ========================================================

    if actual_survived == 1:

        st.success(
            "They survived the Titanic disaster."
        )

        st.markdown(
            f"""
            Your historical counterpart was **{actual_name}**.

            Their circumstances were similar to yours in age, sex,
            passenger class, title, and family situation. The models
            estimated their survival probability at **{actual_probability:.1f}%**.

            In reality, they **survived**.
            """
        )

    else:

        st.error(
            "They did not survive the Titanic disaster."
        )
        st.caption("Estimated probabilities are model predictions, not historical certainties.")

        st.markdown(
            f"""
            Your historical counterpart was **{actual_name}**.

            Their circumstances were similar to yours in age, sex,
            passenger class, title, and family situation. The models
            estimated their survival probability at **{actual_probability:.1f}%**.

            In reality, they **did not survive**.
            """
        )
